Issue103 import uri ext
textX/textX pull request #106
Opened 2018-11-14 20:37 UTC by goto40

Allow python like imports:
```
import folder.module as m
ref m.obj
```

In particular, this extension allows to
 * transform the importURI attribute "a.b" --> e.g., "a/b.ext".
 * allow to control the lookup rules (m.obj instead of obj in the example above).

Affected textx files:  textx/scoping/*

Adapted documentation (scoping.md)

Added new unittests.

2018-11-14 21:53 UTC, goto40 commented
The last two commits (automatic naming of importURI objects, required for the issue103-example) has to be discussed: The name_setter is not the nicest solution. But works (and is somehow similar to the importURI_converter logic)...

2018-11-17 10:05 UTC, igordejanovic requested changes
Great work Pierre. As usual :)
See some inline comments.

I'm thinking about some redesign of textX language to support reference resolving which would hopefully make scoping/resolving more straightforward. Will post as a new issue for discussion.

2018-11-17 10:05 UTC, igordejanovic commented on tests/functional/regressions/test_issue103_python_like_import.py
> +        m = re.search(r'^([^\.]+).*$', import_obj.importURI)
If I understand this regexp, you are collecting everything before the `.`. In that case much simpler would be:
```python
return import_obj.importURI.split('.')[0]
```

2018-11-17 10:05 UTC, igordejanovic commented on tests/functional/regressions/test_issue103_python_like_import.py
> +                                               name_setter=name_setter)})
I'm not happy with the name of this param. `name_setter` is too generic term. Maybe `uri_to_scope_name`? Something more specific but still short enough to be easy to type.

2018-11-17 11:10 UTC, goto40 commented on tests/functional/regressions/test_issue103_python_like_import.py
> +        m = re.search(r'^([^\.]+).*$', import_obj.importURI)
Good point. I also added a comment to make clear what happens here...

2018-11-17 11:19 UTC, goto40 commented on tests/functional/regressions/test_issue103_python_like_import.py
> +                                               name_setter=name_setter)})
I renamed it to importURI_to_scope_name. Good idea, else in two weeks we wonder what name_setter means... ;-)

2018-11-17 11:25 UTC, igordejanovic requested changes
Please see another comment. Sorry for not reporting in the first review.

2018-11-17 11:25 UTC, igordejanovic commented on tests/functional/regressions/test_issue103_python_like_import.py
> +
All path construction should be done by `os.path.join` to prevent cross-platform issues reported in #110. Please correct all instances for this PR and see #110 when find some time.
```python
m = mm.model_from_file(
        join(abspath(dirname(__file__)), "issue103", "main.mod")
```
where `join` is `from os.path import join`

2018-11-17 11:50 UTC, goto40 commented on tests/functional/regressions/test_issue103_python_like_import.py
> +
No problem ;-) I really appreciate this collaboration!

2018-11-17 14:18 UTC, goto40 commented on tests/functional/regressions/test_issue103_python_like_import.py
> +
Uff. There were quite a lot of these... At least I learned something! ;-)

I am not sure if I catched all of them. I also cannot test it using windows. @igordejanovic  can you test it? Else we can ask @dkrikun (see #110).

2018-11-17 14:40 UTC, dkrikun commented
I could test it, but I'm currently a bit struggling with dev. environment
in general, see also #110.

How should one run tests btw, is it `pytest` or `setup.py test`?

On Sat, Nov 17, 2018, 16:18 goto40 <notifications@github.com wrote:

> *@goto40* commented on this pull request.
> ------------------------------
>
> In tests/functional/regressions/test_issue103_python_like_import.py
> <https://github.com/igordejanovic/textX/pull/106#discussion_r234409869>:
>
> > +        # language from the importURI string
> +        # e.g. here: import "file.ext" --> module name "file".
> +        return import_obj.importURI.split('.')[0]
> +
> +    mm.register_scope_providers(
> +        {"*.*": scoping_providers.
> +            FQNImportURI(importAs=True,
> +                         importURI_to_scope_name=importURI_to_scope_name)})
> +
> +    #################################
> +    # MODEL PARSING
> +    #################################
> +
> +    m = mm.model_from_file(
> +        abspath(dirname(__file__)) + "/issue103/main.mod")
> +
>
> Uff. There were quite a lot of these... At least I learned something! ;-)
>
> I am not sure if I catched all of them. I also cannot test it using
> windows. @igordejanovic <https://github.com/igordejanovic> can you test
> it? Else we can ask @dkrikun <https://github.com/dkrikun> (see #110
> <https://github.com/igordejanovic/textX/issues/110>).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/igordejanovic/textX/pull/106#discussion_r234409869>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAfGBDuR7bnD5ctuUVqQBa5lrWOLxrXYks5uwBq5gaJpZM4YeiLP>
> .
>

2018-11-17 14:53 UTC, goto40 commented
It is "py.test tests/functional".
 * You can also have a look at https://github.com/igordejanovic/textX/blob/master/docs/about/contributing.md
 * You can also have a look at ".travis.yml". There you can get hints how the system is setup

2018-11-17 14:59 UTC, igordejanovic commented on tests/functional/regressions/test_issue103_python_like_import.py
> +
@goto40 I don't do windows either ;)

2018-11-17 16:18 UTC, goto40 commented
@dkrikun : if your problems concerning
```
        inner_model = my_model._tx_model_repository.all_models.filename_to_model[
>           abspath(dirname(__file__)) + "/interface_model2/model_b/base.if"]
E       KeyError: 'C:\\proj\\textX\\tests\\functional\\test_scoping/interface_model2/model_b/base.if'
```
are not getting better at all (with the new version from this pull request), tell me...

I expect some of them to go away (or even all).

Note: You may clone "https://github.com/goto40/textX.git"... and checkout the correct branch
```
git clone https://github.com/goto40/textX.git
cd textX
git checkout origin/issue103_importUriExt 
export PYTHONPATH=.
python3 -m pytest tests/functional
```
(Under Windows you may use "set PYTHONPATH=."??)

2018-11-17 17:46 UTC, dkrikun commented
@goto40 much better, only one fail, output attached
[pytest_out.txt](https://github.com/igordejanovic/textX/files/2592083/pytest_out.txt)

2018-11-17 17:58 UTC, igordejanovic commented
@goto40 This could be fixed by changing:
```
assert "inheritance/model_a.a" in text
```
with:
```
assert "inheritance{}model_a.a".format(os.path.sep) in text
```

2018-11-17 18:23 UTC, goto40 commented
Thanks @igordejanovic, fixed.
@dkrikun : You can try again...

2018-11-17 18:38 UTC, dkrikun commented
@goto40 all green

2018-11-17 18:45 UTC, igordejanovic commented
If everything is ok now, @goto40 before merging could you please tidy up history a bit? You can squash last several commits related to cross-platform compatibility fixes in one commit with a proper log message and the rest of the commits, related to import feature, in another.

2018-11-17 18:51 UTC, goto40 commented
I will do it... Best wishes, Pierre

Am Sa., 17. Nov. 2018, 19:45 hat Igor Dejanović <notifications@github.com>
geschrieben:

> If everything is ok now, @goto40 <https://github.com/goto40> before
> merging could you please tidy up history a bit? You can squash last several
> commits related to cross-platform compatibility fixes in one commit with a
> proper log message and the rest of the commits, related to import feature,
> in another.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/igordejanovic/textX/pull/106#issuecomment-439638731>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQGtWkQyITCNPc3vt_ZHHgEHrUb-uhOCks5uwFlIgaJpZM4YeiLP>
> .
>

2018-11-17 21:21 UTC, goto40 commented
closed in favor for #114 (squashed commits)

2018-11-17 21:21 UTC, closed without merging