Add instructions on running mkdocs locally
textX/textX pull request #153
Opened 2018-12-24 21:01 UTC by simkimsia

for the ignorant. Ref https://github.com/igordejanovic/textX/issues/143#issuecomment-449556703

2018-12-25 09:24 UTC, igordejanovic requested changes
Looks good. Just one change is required at the end. Please, see below.

2018-12-25 09:24 UTC, igordejanovic commented on CONTRIBUTING.md
> +To make changes to the configurations, you can look at `mkdocs.yml`. For more information on how to use mkdocs, visit this [site](https://www.mkdocs.org). Essentially, you do not need to install mkdo
Not sure what do you mean by `you do not need to install mkdocs as a software locally...`. You actually do need mkdocs. It is installed as a part of `pip install -r requirements_dev.txt`. See the file, there is `mkdocs` in it. I suggest to remove this sentence entirely as it is confusing.

2018-12-25 10:59 UTC, simkimsia commented on CONTRIBUTING.md
> +To make changes to the configurations, you can look at `mkdocs.yml`. For more information on how to use mkdocs, visit this [site](https://www.mkdocs.org). Essentially, you do not need to install mkdo
Understood. Will make another change and then squash the commits. I have to go get dinner. Then I will come back and fix this asap.

2018-12-25 11:11 UTC, goto40 reviewed
Note : when serving locally some files get generated. Can you check .gitignore if the local docu is correctly ignored.

OK. Just checked. Seems to be OK.

2018-12-25 11:38 UTC, igordejanovic commented on CONTRIBUTING.md
> +To make changes to the configurations, you can look at `mkdocs.yml`. For more information on how to use mkdocs, visit this [site](https://www.mkdocs.org). Essentially, you do not need to install mkdo
Sure. No rush :)

2018-12-25 12:46 UTC, simkimsia commented on CONTRIBUTING.md
> +To make changes to the configurations, you can look at `mkdocs.yml`. For more information on how to use mkdocs, visit this [site](https://www.mkdocs.org). Essentially, you do not need to install mkdo
@igordejanovic done. I force pushed the squash. It should be updated soon.

2019-01-11 18:07 UTC, igordejanovic commented
Thanks. Merging.

2019-01-11 18:07 UTC, merged